# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - llmsherpa-ingestor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a7596ef1695247c9af5b026320afe20d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_827d5731f6694012a9ae2e9b347e2dc5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_a7596ef1695247c9af5b026320afe20d }}/nlm-ingestor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'llmsherpa-ingestor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a4fdee99eef14b488d19c2e7411952c8 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_a7596ef1695247c9af5b026320afe20d }}/nlm-ingestor:${{ github.sha }}'